title: "PixelDINO"
baseURL: "https://khdlr.github.io/PixelDINO/"
languageCode: "en-GB"
theme: "github.com/khdlr/osprey-delight/v5"
tags: ["personal", "homepage", "portfolio"]
canonifyURLS: true
#googleAnalytics: ""
disableKinds: ["taxonomy", "taxonomyTerm"]
enableEmoji: true
pygmentsUseClasses: true
markup:
  goldmark:
    renderer:
      unsafe: true

module:
  imports:
  - path: github.com/khdlr/osprey-delight/v5

## Generic theme parameters:
Params:
  author: "Konrad Heidler"
  description: "PixelDINO: Semi-Supervised Semantic Segmentation for Detecting Permafrost Disturbances"

  # logoBig appears at the top of the page. Use a path relative to the assets dir for auto-resizing. 
  logoBig: "1x1.png"

  # logoSmall is the logo that will be shown in the left corner of the nav bar.
  #   Use a path relative to the assets dir for auto-resizing.
  logoSmall: "1x1.png"

  # background can optionally be specified as an image layer behind logoBig at the top of the page (parallax effect).
  background: "background.jpg"
  #
  # opengraphImage specifies the image that is shown when previewing the site in a messenger or Google Search.
  opengraphImage: "helheim_overlay.png"

  # favicon of the site (e.g. smaller version of logoSmall).
  # favicon: "favicon.png"

  # theme your site by choosing one of the themes under assets/sass/themes:
  #   - delight is the light version of osprey-delight
  #   - dedark is the dark version of "delight"
  #   - origin is the legacy version (similar to https://github.com/tomanistor/osprey)
  theme: "delight"

  mdTagline: |
    # PixelDINO: Semi-Supervised Semantic Segmentation for Detecting Permafrost Disturbances

  # enforceSinglePage will enforce redirection to the baseURL for all sub-directories/-pages.
  #   Example: If you create about.md, Hugo will also create a '/about/index.html' which might not be what you want for a *single* page site. 
  #   If this switch is enabled, all these "orphan" files will contain only a redirect directive.
  enforceSinglePage: true

  # copyright flag generates a copyright notice in footer of your site.
  copyright: true

  # credit to the theme. If you want to support the theme by please leave this in, it's kept very tiny and short.
  # credit: true

## Additional theme features:
  Feat:
    # ajaxBasin requires Basin setup for a free contact form (see instructions in README).
    ajaxBasin: "https://usebasin.com/f/{YOUR-12-CHAR-FORM-KEY-HERE}"

    # useStructuredData for your own https://schema.org/Person (SEO-friendly).
    #   This will be auto-generated dependent on the information you provide in this configuration.
    useStructuredData: false

    # structuredDataGitHubUser will tell the theme to use your USERNAME for querying the GitHub API to fetch more information about you for structured data.
    #   This will use information that is publically available about your GitHub user profile at https://api.github.com/users/{USERNAME}.
    #structuredDataGitHubUser = "USERNAME"

    # useTermynal enables Termynal (https://github.com/ines/termynal), a small JS library for showing a terminal "animation" from within your gallery item.
    #   The library has been stripped-down to a minimum to only have the necessary functionality.
    useTermynal: true

    googleTagManager: ""

    # notifyOnNewThemeVersion enables a notification for every new minor/major version of this theme.
    #   Whenever there is a new one, a warning is printed to console.
    notifyOnNewThemeVersion: true
  
  # Image resizing can be configured here (see README for more info):
  Image:
    Logo:
      resize: "600x"

    Gallery:
      resize: "600x"

    Background:
      resize: "1920x"
      resizeLQIP: "256x"

  # Advanced configuration for lazyimg module (comment out if needed):
  # lazyimg:
  #   resizer: auto
  #   renderer: lqip-webp

  #   # Resizer options:
  #   lqipSize: "120x Gaussian"
  #   maxSize: "1920x"
  #   responsiveSizes: ["320x", "640x", "768x", "1024x", "1366x", "1600x", "1920x"]
  #   resizeOptions: "Lanczos q95"

  #   # Renderer options:
  #   #class: ""
  #   #alt: ""
  #   noscript: true

## Menu items are automatically added to navbar.
##   See: https://gohugo.io/content-management/menus/#add-content-to-menus
Menu:
  Main:
    # - name: "Idea"
    #   # identifier controls the section type (and therewith the appearence).
    #   identifier: idea
    #   # url must be an anchor, for smooth scrolling to it when clicking on the menu item.
    #   url: "/#idea"
    #   # weight controls the order of the menu items.
    #   weight: 1
    - name: Method
      identifier: pixeldino
      url: "/#pixeldino"
      weight: 2
    - name: Results
      identifier: results
      url: "/#results"
      weight: 3
    - name: Paper
      identifier: paper
      url: "/#paper"
      weight: 10
    - name: "Code"
      identifier: code
      url: "/#code"
      weight: 20
    # - name: "Map"
    #   identifier: map
    #   url: "/#map"
    #   weight: 40
    # - name: "Work"
    #   identifier: gallery
    #   url: "/#work"
    #   weight: 400
    # - name: ""
    #   # pre makes it possible to use arbitrary HTML before the name, e.g. referencing icons here is possible:
    #   pre: '<svg class="icon"><use xlink:href="#icon-external"/></svg>&nbsp;'
    #   url: "https://pyotek.dev"
    #   weight: 5
