# Model Specification
model: MultitaskHEDUNet
model_args:
  input_spec:
    SAR: 1
    Sentinel2: 12
    Landsat8: 11
    Landsat7: 9
    Landsat45: 7
  output_spec:
    Fronts:
      classes: 1
      loss: AutoBCE
    Mask:
      classes: 1
      loss: CrossEntropy
    Termpicks:
      classes: 1
      loss: AutoBCE
    Kochtitzky:
      classes: 1
      loss: AutoBCE
    Zones:
      classes: 4
      loss: CrossEntropy
  base_channels: 16
  stack_height: 5
  batch_norm: true
# Training Parameters
tile_size: 512
data_root: '/home/user/_data/FromTian'
feature_pyramid: true
batch_size: 16
epochs: 100
learning_rate: 1.e-3
# Data Configuration
data_threads: 4
# Visualization
