# Model Specification
model: MultitaskHEDUNet
model_args:
  input_spec:
    SAR: 1
    Sentinel2: 11
    Landsat8: 10
    Landsat8_Normalized: 10
    Landsat7: 8
    Landsat45: 7
  output_spec:
    Fronts:
      classes: 1
      loss: NoSigmoidAutoBCE
    Mask:
      classes: 1
      loss: CrossEntropy
    Termpicks:
      classes: 1
      loss: NoSigmoidAutoBCE
    Kochtitzky:
      classes: 1
      loss: NoSigmoidAutoBCE
    TUD_Fronts:
      classes: 1
      loss: NoSigmoidAutoBCE
    Zones:
      classes: 4
      loss: CrossEntropy
  base_channels: 16
  stack_height: 5
  batch_norm: false
# Training Parameters
tile_size: 512
data_root: '/data/Konrad_Tian_SharedFolder/TrainingData/'
feature_pyramid: true
batch_size: 8
epochs: 300
learning_rate: 1.e-3
# Data Configuration
data_threads: 12
# Visualization
