# Model Specification
model: HEDUNet
model_args:
  input_channels: 2
  base_channels: 8
  stack_height: 5
  side_channels: 0
  merging: attention
# Training Parameters
feature_pyramid: true
loss_function:
  type: AutoBCE
batch_size: 4
learning_rate: 0.001
schedule:
  - phase: Training
    epochs: 15
    steps:
      - train_on: train
      - validate_on: val
      - log_images
# Data Configuration
data_threads: 4
datasets:
  train:
    augment: true
    shuffle: true
    folders:
      - "Example Folder 1"
      - "Example Folder 2"
      # ...
  val:
    augment: false
    shuffle: false
    folders:
      - "Example Folder 3"
      # ...
# Visualization
visualization_tilesj
  - "Example Folder 3/16"
  # ...
